# Generated by Django 2.1.1 on 2020-05-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
